# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BulldogAgenda' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BulldogAgenda
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'

  target 'BulldogAgendaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
